name: trigger travis

on: ['push', 'pull_request']

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate API module
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "lxf1"
          git config --global user.email "954055752@qq.com"
          git clone https://user:$GITHUB_TOKEN@github.com/lxfu1/release-inspection-of-antv.git

          cd release-inspection-of-antv
          git checkout -b api-version
          git remote add api-version https://user:$GITHUB_TOKEN@github.com/lxfu1/release-inspection-of-antv.git

          echo config list

          git config --list

          echo remote

          git remote -v
          touch new-file.sh
          git add new-file.sh
          git commit --message 'Trigger travis actions'

          echo status

          git status
          git push --set-upstream origin api-version
          # git push --set-upstream https://user:$GITHUB_TOKEN@github.com/lxfu1/release-inspection-of-antv.git api-version # This does not work either
      # - name: Pushes a file to release-inspection-of-antv
      #   uses: dmnemec/copy_file_to_another_repo_action@main
      #   env:
      #     API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      #   with:
      #     source_file: '.prettierrc'
      #     destination_repo: 'lxfu1/release-inspection-of-antv'
      #     destination_folder: 'server'
      #     user_email: '954055752@qq.com'
      #     user_name: 'lxfu1'
      #     commit_message: 'Trigger travis actions'
      #     destination_branch: 'master'
